import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  WorkspaceCreatedPayload as ContractsWorkspaceCreatedPayloadSchema,
  WorkspaceArchivedPayload as ContractsWorkspaceArchivedPayloadSchema,
  WorkspaceMetaUpdatedPayload as ContractsWorkspaceMetaUpdatedPayloadSchema,
  WorkspaceRuntimeModeSetPayload as ContractsWorkspaceRuntimeModeSetPayloadSchema,
  WorkspaceInteractionModeSetPayload as ContractsWorkspaceInteractionModeSetPayloadSchema,
  WorkspaceDeletedPayload as ContractsWorkspaceDeletedPayloadSchema,
  WorkspaceUnarchivedPayload as ContractsWorkspaceUnarchivedPayloadSchema,
  WorkspaceMessageSentPayload as ContractsWorkspaceMessageSentPayloadSchema,
  WorkspaceProposedPlanUpsertedPayload as ContractsWorkspaceProposedPlanUpsertedPayloadSchema,
  WorkspaceSessionSetPayload as ContractsWorkspaceSessionSetPayloadSchema,
  WorkspaceTurnDiffCompletedPayload as ContractsWorkspaceTurnDiffCompletedPayloadSchema,
  WorkspaceRevertedPayload as ContractsWorkspaceRevertedPayloadSchema,
  WorkspaceActivityAppendedPayload as ContractsWorkspaceActivityAppendedPayloadSchema,
  WorkspaceTurnStartRequestedPayload as ContractsWorkspaceTurnStartRequestedPayloadSchema,
  WorkspaceTurnInterruptRequestedPayload as ContractsWorkspaceTurnInterruptRequestedPayloadSchema,
  WorkspaceApprovalResponseRequestedPayload as ContractsWorkspaceApprovalResponseRequestedPayloadSchema,
  WorkspaceCheckpointRevertRequestedPayload as ContractsWorkspaceCheckpointRevertRequestedPayloadSchema,
  WorkspaceSessionStopRequestedPayload as ContractsWorkspaceSessionStopRequestedPayloadSchema,
} from "@matcha/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const WorkspaceCreatedPayload = ContractsWorkspaceCreatedPayloadSchema;
export const WorkspaceArchivedPayload = ContractsWorkspaceArchivedPayloadSchema;
export const WorkspaceMetaUpdatedPayload = ContractsWorkspaceMetaUpdatedPayloadSchema;
export const WorkspaceRuntimeModeSetPayload = ContractsWorkspaceRuntimeModeSetPayloadSchema;
export const WorkspaceInteractionModeSetPayload = ContractsWorkspaceInteractionModeSetPayloadSchema;
export const WorkspaceDeletedPayload = ContractsWorkspaceDeletedPayloadSchema;
export const WorkspaceUnarchivedPayload = ContractsWorkspaceUnarchivedPayloadSchema;

export const MessageSentPayloadSchema = ContractsWorkspaceMessageSentPayloadSchema;
export const WorkspaceProposedPlanUpsertedPayload =
  ContractsWorkspaceProposedPlanUpsertedPayloadSchema;
export const WorkspaceSessionSetPayload = ContractsWorkspaceSessionSetPayloadSchema;
export const WorkspaceTurnDiffCompletedPayload = ContractsWorkspaceTurnDiffCompletedPayloadSchema;
export const WorkspaceRevertedPayload = ContractsWorkspaceRevertedPayloadSchema;
export const WorkspaceActivityAppendedPayload = ContractsWorkspaceActivityAppendedPayloadSchema;

export const WorkspaceTurnStartRequestedPayload = ContractsWorkspaceTurnStartRequestedPayloadSchema;
export const WorkspaceTurnInterruptRequestedPayload =
  ContractsWorkspaceTurnInterruptRequestedPayloadSchema;
export const WorkspaceApprovalResponseRequestedPayload =
  ContractsWorkspaceApprovalResponseRequestedPayloadSchema;
export const WorkspaceCheckpointRevertRequestedPayload =
  ContractsWorkspaceCheckpointRevertRequestedPayloadSchema;
export const WorkspaceSessionStopRequestedPayload =
  ContractsWorkspaceSessionStopRequestedPayloadSchema;
